# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1845, 1065)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1845, 23))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuCamera_Preview = QtWidgets.QMenu(self.menubar)
        self.menuCamera_Preview.setObjectName("menuCamera_Preview")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionUsers = QtWidgets.QAction(MainWindow)
        self.actionUsers.setObjectName("actionUsers")
        self.actionVehicles = QtWidgets.QAction(MainWindow)
        self.actionVehicles.setObjectName("actionVehicles")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionAssignment = QtWidgets.QAction(MainWindow)
        self.actionAssignment.setObjectName("actionAssignment")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionMultipleCameras = QtWidgets.QAction(MainWindow)
        self.actionMultipleCameras.setObjectName("actionMultipleCameras")
        self.menuSettings.addAction(self.actionUsers)
        self.menuSettings.addAction(self.actionVehicles)
        self.menuSettings.addAction(self.actionAssignment)
        self.menuSettings.addAction(self.actionClose)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionLogout)
        self.menuCamera_Preview.addAction(self.actionMultipleCameras)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuCamera_Preview.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuSettings.setTitle(_translate("MainWindow", "Options"))
        self.menuCamera_Preview.setTitle(_translate("MainWindow", "Camera Preview"))
        self.actionUsers.setText(_translate("MainWindow", "Users"))
        self.actionVehicles.setText(_translate("MainWindow", "Vehicles"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionAssignment.setText(_translate("MainWindow", "Assignment"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionMultipleCameras.setText(_translate("MainWindow", "Multiple Cameras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
