# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraPreviewView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraPreviewView(object):
    def setupUi(self, CameraPreviewView):
        CameraPreviewView.setObjectName("CameraPreviewView")
        CameraPreviewView.resize(417, 425)
        self.vertLayCamPreview = QtWidgets.QVBoxLayout(CameraPreviewView)
        self.vertLayCamPreview.setContentsMargins(2, 2, 2, -1)
        self.vertLayCamPreview.setObjectName("vertLayCamPreview")
        self.groupBox = QtWidgets.QGroupBox(CameraPreviewView)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbTextDetails = QtWidgets.QLabel(self.groupBox)
        self.lbTextDetails.setMinimumSize(QtCore.QSize(0, 40))
        self.lbTextDetails.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lbTextDetails.setText("")
        self.lbTextDetails.setObjectName("lbTextDetails")
        self.verticalLayout.addWidget(self.lbTextDetails)
        self.lbCameraPreview = QtWidgets.QLabel(self.groupBox)
        self.lbCameraPreview.setMinimumSize(QtCore.QSize(0, 200))
        self.lbCameraPreview.setText("")
        self.lbCameraPreview.setObjectName("lbCameraPreview")
        self.verticalLayout.addWidget(self.lbCameraPreview)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.vertLayCamPreview.addWidget(self.groupBox)

        self.retranslateUi(CameraPreviewView)
        QtCore.QMetaObject.connectSlotsByName(CameraPreviewView)

    def retranslateUi(self, CameraPreviewView):
        _translate = QtCore.QCoreApplication.translate
        CameraPreviewView.setWindowTitle(_translate("CameraPreviewView", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraPreviewView = QtWidgets.QWidget()
    ui = Ui_CameraPreviewView()
    ui.setupUi(CameraPreviewView)
    CameraPreviewView.show()
    sys.exit(app.exec_())
