# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UsersView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Users(object):
    def setupUi(self, Users):
        Users.setObjectName("Users")
        Users.resize(977, 520)
        self.gridLayout_2 = QtWidgets.QGridLayout(Users)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(Users)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Users)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.leLogin = QtWidgets.QLineEdit(self.groupBox)
        self.leLogin.setObjectName("leLogin")
        self.verticalLayout.addWidget(self.leLogin)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lePasswd = QtWidgets.QLineEdit(self.groupBox)
        self.lePasswd.setObjectName("lePasswd")
        self.verticalLayout.addWidget(self.lePasswd)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.leName = QtWidgets.QLineEdit(self.groupBox)
        self.leName.setObjectName("leName")
        self.verticalLayout.addWidget(self.leName)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.leSurname = QtWidgets.QLineEdit(self.groupBox)
        self.leSurname.setObjectName("leSurname")
        self.verticalLayout.addWidget(self.leSurname)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.groupBox)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnUpdate = QtWidgets.QPushButton(self.groupBox)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout.addWidget(self.btnUpdate)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btnDelete = QtWidgets.QPushButton(self.groupBox)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.btnClose = QtWidgets.QPushButton(self.groupBox)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(Users)
        QtCore.QMetaObject.connectSlotsByName(Users)

    def retranslateUi(self, Users):
        _translate = QtCore.QCoreApplication.translate
        Users.setWindowTitle(_translate("Users", "Form"))
        self.groupBox.setTitle(_translate("Users", "Options"))
        self.label.setText(_translate("Users", "Login:"))
        self.label_2.setText(_translate("Users", "Password:"))
        self.label_3.setText(_translate("Users", "Name"))
        self.label_4.setText(_translate("Users", "Surname"))
        self.btnAdd.setText(_translate("Users", "Add"))
        self.btnUpdate.setText(_translate("Users", "Update"))
        self.btnDelete.setText(_translate("Users", "Delete"))
        self.btnClose.setText(_translate("Users", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Users = QtWidgets.QWidget()
    ui = Ui_Users()
    ui.setupUi(Users)
    Users.show()
    sys.exit(app.exec_())
