# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultipleVehiclesPreviewView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultipleVehiclesPreview(object):
    def setupUi(self, MultipleVehiclesPreview):
        MultipleVehiclesPreview.setObjectName("MultipleVehiclesPreview")
        MultipleVehiclesPreview.resize(1268, 717)
        self.gridLayout = QtWidgets.QGridLayout(MultipleVehiclesPreview)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.gpbMultipleVehiclesPreview = QtWidgets.QGroupBox(MultipleVehiclesPreview)
        self.gpbMultipleVehiclesPreview.setObjectName("gpbMultipleVehiclesPreview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gpbMultipleVehiclesPreview)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.gpbMultipleVehiclesPreview)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1252, 681))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridMultipleVehiclesPreview = QtWidgets.QGridLayout()
        self.gridMultipleVehiclesPreview.setObjectName("gridMultipleVehiclesPreview")
        self.gridLayout_4.addLayout(self.gridMultipleVehiclesPreview, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gpbMultipleVehiclesPreview, 0, 0, 1, 1)

        self.retranslateUi(MultipleVehiclesPreview)
        QtCore.QMetaObject.connectSlotsByName(MultipleVehiclesPreview)

    def retranslateUi(self, MultipleVehiclesPreview):
        _translate = QtCore.QCoreApplication.translate
        MultipleVehiclesPreview.setWindowTitle(_translate("MultipleVehiclesPreview", "Form"))
        self.gpbMultipleVehiclesPreview.setTitle(_translate("MultipleVehiclesPreview", "Multiple vehicles preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MultipleVehiclesPreview = QtWidgets.QWidget()
    ui = Ui_MultipleVehiclesPreview()
    ui.setupUi(MultipleVehiclesPreview)
    MultipleVehiclesPreview.show()
    sys.exit(app.exec_())
