# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SingleVehiclesPreviewView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleVehiclesPreview(object):
    def setupUi(self, SingleVehiclesPreview):
        SingleVehiclesPreview.setObjectName("SingleVehiclesPreview")
        SingleVehiclesPreview.resize(1268, 717)
        self.gridLayout = QtWidgets.QGridLayout(SingleVehiclesPreview)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gpbSingleVehiclesPreview = QtWidgets.QGroupBox(SingleVehiclesPreview)
        self.gpbSingleVehiclesPreview.setObjectName("gpbSingleVehiclesPreview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gpbSingleVehiclesPreview)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gbDetails = QtWidgets.QGroupBox(self.gpbSingleVehiclesPreview)
        self.gbDetails.setMinimumSize(QtCore.QSize(300, 200))
        self.gbDetails.setObjectName("gbDetails")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbDetails)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblVehicleData = QtWidgets.QLabel(self.gbDetails)
        self.lblVehicleData.setObjectName("lblVehicleData")
        self.verticalLayout.addWidget(self.lblVehicleData)
        self.cbVehicleChoice = QtWidgets.QComboBox(self.gbDetails)
        self.cbVehicleChoice.setObjectName("cbVehicleChoice")
        self.verticalLayout.addWidget(self.cbVehicleChoice)
        self.btnMultiVehicle = QtWidgets.QPushButton(self.gbDetails)
        self.btnMultiVehicle.setObjectName("btnMultiVehicle")
        self.verticalLayout.addWidget(self.btnMultiVehicle)
        self.gridLayout_3.addWidget(self.gbDetails, 1, 1, 1, 1)
        self.gbCamRight = QtWidgets.QGroupBox(self.gpbSingleVehiclesPreview)
        self.gbCamRight.setObjectName("gbCamRight")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gbCamRight)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.glCamRight = QtWidgets.QGridLayout()
        self.glCamRight.setObjectName("glCamRight")
        self.verticalLayout_5.addLayout(self.glCamRight)
        self.gridLayout_3.addWidget(self.gbCamRight, 0, 1, 1, 1)
        self.gbCamLeft = QtWidgets.QGroupBox(self.gpbSingleVehiclesPreview)
        self.gbCamLeft.setObjectName("gbCamLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbCamLeft)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.glCamLeft = QtWidgets.QGridLayout()
        self.glCamLeft.setObjectName("glCamLeft")
        self.verticalLayout_2.addLayout(self.glCamLeft)
        self.gridLayout_3.addWidget(self.gbCamLeft, 0, 0, 1, 1)
        self.gbCamFe = QtWidgets.QGroupBox(self.gpbSingleVehiclesPreview)
        self.gbCamFe.setObjectName("gbCamFe")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbCamFe)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.glCamFe = QtWidgets.QGridLayout()
        self.glCamFe.setObjectName("glCamFe")
        self.verticalLayout_4.addLayout(self.glCamFe)
        self.gridLayout_3.addWidget(self.gbCamFe, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.gpbSingleVehiclesPreview)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(SingleVehiclesPreview)
        QtCore.QMetaObject.connectSlotsByName(SingleVehiclesPreview)

    def retranslateUi(self, SingleVehiclesPreview):
        _translate = QtCore.QCoreApplication.translate
        SingleVehiclesPreview.setWindowTitle(_translate("SingleVehiclesPreview", "Form"))
        self.gpbSingleVehiclesPreview.setTitle(_translate("SingleVehiclesPreview", "Single Vehicle Preview"))
        self.gbDetails.setTitle(_translate("SingleVehiclesPreview", "Details"))
        self.lblVehicleData.setText(_translate("SingleVehiclesPreview", "TextLabel"))
        self.btnMultiVehicle.setText(_translate("SingleVehiclesPreview", "Close"))
        self.gbCamRight.setTitle(_translate("SingleVehiclesPreview", "Cam Right"))
        self.gbCamLeft.setTitle(_translate("SingleVehiclesPreview", "Cam Left"))
        self.gbCamFe.setTitle(_translate("SingleVehiclesPreview", "Cam Fish Eye"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleVehiclesPreview = QtWidgets.QWidget()
    ui = Ui_SingleVehiclesPreview()
    ui.setupUi(SingleVehiclesPreview)
    SingleVehiclesPreview.show()
    sys.exit(app.exec_())
